### PR TITLE
Use `forceX` and `forceY` instead of `forceCenter`

### PR DESCRIPTION
**Pull request by phenomnomnominal**
This seems to work and doesn't seem to be breaking anything else?

### Before:
Screen Shot 2022-05-08 at 18 35 49

### After:
Screen Shot 2022-05-08 at 18 35 35

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by phenomnomnominal** [comment]
Oh I get it, doesn’t work with 3d

**Comment by amcdnl** [comment]
Its fine - 3d is less a problem imo

**Review by amcdnl — COMMENTED** [review]
lgtm

**Comment by phenomnomnominal** [comment]
Been looking into the force layout thing some more, and it seems like it's a bunch of trade offs. The connected parts of the graph and kept at the same distance with the link force, and if you want them dispersed nicely you need the manyBody force set to highly repulsive - but that's what makes the non-connected parts of the graph fly far away.

So you can either have the disjointed parts of the graph clustered together with some uneven distribution of the connected nodes, or nicely distributed connected nodes with large distances between disjointed parts of the graph.

I think this combo is a decent balance between the two.

**Pull request merged**
