### PR TITLE
#61 - Migrate to Graphology

### PR DESCRIPTION
**Pull request by amcdnl**
This PR:

- Migrates from ngraph to graphology
- Fixes node drag bug
- Adds no overlap layout
- Adds forceatlas2 layout
- Removed lodash
- Doc Cleanup

### CODE REVIEW

**Comment by Marrocco-Simone** [comment]
I get this error with the new version in nextjs 13:
```
- error Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path_to_project/node_modules/graphology-layout/circular' imported from /path_to_project/node_modules/reagraph/dist/index.js
Did you mean to import graphology-layout/circular.js?
    at new NodeError (node:internal/errors:400:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:834:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:415:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  digest: undefined
}
```

**Comment by amcdnl** [comment]
Did the previous version work?

**Comment by Marrocco-Simone** [comment]
Yes, it works

**Comment by amcdnl** [comment]
Thank you - was just trying to isolate the issue.

**Comment by benjick** [comment]
Any workaround?

**Comment by amcdnl** [comment]
> Any workaround?

It should be fixed - let me know if not

**Comment by benjick** [comment]
@amcdnl I just generated a new NextJS project using t3 (https://t3.gg/) and installed the package: `"reagraph": "^4.13.0",`

Then I just followed the basics example, from here: https://reagraph.dev/?path=/docs/docs-getting-started-basics--docs

Giving me the following error:

```
Error: Cannot find module '/Users/max/dev/docker-vis/node_modules/graphology-layout/circular' imported from /Users/max/dev/docker-vis/node_modules/reagraph/dist/index.js
Did you mean to import graphology-layout/circular.js?
```

**Pull request merged**
